### ISSUE TITLE
Curation review request breaks apart when `publication_date` is not set

### ISSUE THREAD

**Issue by max-moser** [tu-graz-library/invenio-curations#19]
When the `publication_date` field for the record's metadata is not set, then visiting the `rdm-curation` request's timeline UI falls apart.
This is especially annoying with "new versions" of records, since the publication date field gets wiped for some reason.

```
127.0.0.1 - - [17/Sep/2024 18:57:13] "GET /me/requests/f818d51d-ed89-417a-afdd-74a24e4b2c32 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.12/site-packages/flask/app.py", line 2552, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.12/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.12/site-packages/werkzeug/middleware/dispatcher.py", line 78, in __call__
    return app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.12/site-packages/flask/app.py", line 2532, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.12/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.12/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.12/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.12/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.12/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.12/site-packages/invenio_requests/views/decorators.py", line 30, in view
    return f(**kwargs)
           ^^^^^^^^^^^
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.12/site-packages/invenio_app_rdm/requests_ui/views/requests.py", line 184, in user_dashboard_request_view
    return render_template(
           ^^^^^^^^^^^^^^^^
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.12/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.12/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.12/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/mmoser/rdm/modules/invenio-curations/invenio_curations/templates/semantic-ui/invenio_requests/rdm-curation/index.html", line 16, in top-level template code
    {% set active_dashboard_menu_item = "curation-overview" if is_curator else "requests" %}
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.12/site-packages/invenio_requests/templates/semantic-ui/invenio_requests/details/index.html", line 90, in top-level template code
    {% block javascript %}
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.12/site-packages/invenio_app_rdm/users_ui/templates/semantic-ui/invenio_app_rdm/users/base.html", line 8, in top-level template code
    {%- extends config.BASE_TEMPLATE %}
  File "/home/mmoser/rdm/modules/invenio-theme-tuw/invenio_theme_tuw/theme/templates/semantic-ui/invenio_theme_tuw/overrides/page.html", line 98, in top-level template code
    {%- block body %}
  File "/home/mmoser/rdm/modules/invenio-theme-tuw/invenio_theme_tuw/theme/templates/semantic-ui/invenio_theme_tuw/overrides/page.html", line 107, in block 'body'
    {%- block body_inner %}
  File "/home/mmoser/rdm/modules/invenio-theme-tuw/invenio_theme_tuw/theme/templates/semantic-ui/invenio_theme_tuw/overrides/page.html", line 203, in block 'body_inner'
    {%- block page_body %}
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.12/site-packages/invenio_requests/templates/semantic-ui/invenio_requests/details/index.html", line 21, in block 'page_body'
    {%- block request_body %}
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.12/site-packages/invenio_requests/templates/semantic-ui/invenio_requests/details/index.html", line 46, in block 'request_body'
    {%- block request_timeline %}
  File "/home/mmoser/rdm/modules/invenio-curations/invenio_curations/templates/semantic-ui/invenio_requests/rdm-curation/index.html", line 88, in block 'request_timeline'
    {% include "invenio_app_rdm/records/detail.html" %}
  File "/home/mmoser/rdm/modules/invenio-theme-tuw/invenio_theme_tuw/theme/templates/semantic-ui/invenio_app_rdm/records/detail.html", line 39, in top-level template code
    {%- block tuw_metadata -%}
  File "/home/mmoser/rdm/modules/invenio-theme-tuw/invenio_theme_tuw/theme/templates/semantic-ui/invenio_app_rdm/records/detail.html", line 41, in block 'tuw_metadata'
    {%- set schemaorg_metadata = tuw_create_schemaorg_metadata(record) %}
  File "/home/mmoser/rdm/modules/invenio-theme-tuw/invenio_theme_tuw/views.py", line 210, in tuw_create_schemaorg_metadata
    return SchemaorgJSONLDSerializer().serialize_object(record)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.12/site-packages/flask_resources/serializers/base.py", line 77, in serialize_object
    return self.format_serializer.serialize_object(self.dump_obj(obj))
                                                   ^^^^^^^^^^^^^^^^^^^
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.12/site-packages/flask_resources/serializers/base.py", line 66, in dump_obj
    return self.object_schema.dump(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.12/site-packages/marshmallow/schema.py", line 553, in dump
    result = self._serialize(processed_obj, many=many)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.12/site-packages/marshmallow/schema.py", line 521, in _serialize
    value = field_obj.serialize(attr_name, obj, accessor=self.get_attribute)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.12/site-packages/marshmallow/fields.py", line 341, in serialize
    return self._serialize(value, attr, obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.12/site-packages/marshmallow/fields.py", line 1985, in _serialize
    return self._serialize_method(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.12/site-packages/invenio_rdm_records/resources/serializers/schemaorg/schema.py", line 234, in get_publication_date
    parsed_date = parse_edtf(py_.get(obj, "metadata.publication_date"))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.12/site-packages/babel_edtf/__init__.py", line 202, in parse_edtf
    if len(date) == 10:
       ^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
```

**Comment by rekt-hard** [comment]
see also https://github.com/inveniosoftware/invenio-rdm-records/issues/1732

**Comment by max-moser** [comment]
Indeed, it was the same issue.
Closing as the issue was fixed.
